-   name: Test connectivity to target servers
    hosts: '{{ arg_host }}'
    tasks:
      - name: ping
        ping:

      - name: check date
        command: date
        register: out
      - debug: msg="{{ out.stdout }}"
      - debug: msg="{{ out.stderr }}"
